config/routes.rb
Superette::Application.routes.draw do  
	
	match ':slug/:controller(/:action(/:id(.:format)))'
  
  resources :stuffs

  get "shops/index"

  get "login/index"
  
  resources :shops

  root :to => 'landing#index'

   match ':controller(/:action(/:id(.:format)))'
end

app/models/shop.rb
class Shop < ActiveRecord::Base
	validates :name, :uniqueness => true
	validates :email, :uniqueness => true
	validates :slug, :uniqueness => true
	
	validates :name, :presence => true
	validates :email, :presence => true
	validates :slug, :presence => true
	
	validates :password, :presence => true
	
	has_many :stuffs
	has_many :invoices
	has_one :paypal_account
	accepts_nested_attributes_for :paypal_account
	
	
	def self.authenticate(email = "", password = "")
		return false if password == ""
		return false if email == ""
		return true if find(:all, :conditions=>["email = ? and password = password(?)", email, password]).length > 0
	end
	
	def reset(request = nil)
		return false if request == nil
		return false if pendingpassword == nil
		
		self.password = pendingpassword if verification == request
		
		return verification == request
	end
	
	def initiatereset
		hash = rand(36**16).to_s(36)
		self.pendingpassword = Shop.find_by_sql(["select password( ? ) as pass", hash])[0].pass
		self.verification = hash
		
		#todo - send email
		
		return true
	end
	
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
	before_filter :check_auth

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @shops }
    end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @shop = Shop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @shop }
    end
  end

  # GET /shops/new
  # GET /shops/new.json
  def new
  	  @action = "create"
    @shop = Shop.new
    @shop.build_paypal_account

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @shop }
    end
  end

  # GET /shops/1/edit
  def edit

  	  @action = "update"
    @shop = Shop.find(params[:id])
  	  if !@edit
  	  	  redirect_to (@shop) and return
  	  end
	  @shop.build_paypal_account if not @shop.paypal_account
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(params[:shop])

    respond_to do |format|
      if @shop.save
        format.html { redirect_to "/#{@shop.slug}/shops/edit/#{@shop.id}", :notice => 'Shop was successfully created.' }
        format.json { render :json => @shop, :status => :created, :location => @shop }
      else
        format.html { render :action => "new" }
        format.json { render :json => @shop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shops/1
  # PUT /shops/1.json
  def update
    @shop = Shop.find(params[:id])
    #params[:shop][:slug] = params[:shop][:slug].strip.downcase.gsub(/[^a-z0-9]+/,'-')
    respond_to do |format|
      if @shop.update_attributes(params[:shop])
      	      notice = 'Shop was successfully updated.'
      	      if ( (params[:superpass] == params[:retype]) && (params[:retype] != ""))
      	      	      @shop.password = Shop.find_by_sql(["select password( ? ) as pass", params[:superpass]])[0].pass
      	      	      @shop.save
      	      	      notice += '<br />Shop password was updated!'
      	      end
        format.html { redirect_to "/#{@shop.slug}/shops/edit/#{@shop.id}", :notice => notice }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @shop.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url }
      format.json { head :ok }
    end
  end

  def check_auth
  	  @edit = false
  	  @edit = true if session["authenticated"]
		
  end

end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_for(@shop, :url=>{ :action=>@action, :id=>@shop.id }) do |f| %>
  <% if @shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% @shop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%if notice%>
  <p id="notice" style="display:none;"><%=raw notice %></p>
  <script>
  	$('#notice').slideDown(400);
  	$('#notice').delay(4000).slideUp(400);
  </script>
  <%end%>
  
  <div class="subtitle box">Your Shop</div>
  <div class="fields">
  	<%if @shop.id%>
		<div style="display:inline; float:right; text-align:right; font-size:0.7em; color:#444444;">
		<%=link_to image_tag(gravatar_url(@shop.email, {:size=>"100"}), :class=>"box"), "http://www.gravatar.com"%><br />
		Update your Gravatar!
		</div>
  	<%end%>
  	<table>
		<tr>
			<td class="field_header"><%= f.label :name %></td>
			<td><%= f.text_field :name %></td>
		</tr>
		<tr>
			<td class="field_header"><%= f.label :email %></td>
			<td><%= f.text_field :email %></td>
		</tr>
		<tr>
			<td class="field_header">Custom URL:</td>
			<td><%= f.text_field :slug %></td>
		</tr>
		<tr>
			<td colspan=2 class="description">http://localhost:3000/<span id="url"><%=@shop.slug%></span>/store</td>
		</tr>                
                <tr>
                        <td class="field_header">Shop Description:</td>
                        <td><%= f.text_area :description, :rows=> 6, :placeholder=>"Put your shop address, phone, slogan and other descriptive info here." %></td>
                </tr>
		<tr>
			<td class="field_header">Password:</td>
			<td><input type="password" name="superpass" size=30 placeholder="Change your password?"></td>
		</tr>
		<tr>
			<td class="field_header">Re-type:</td>
			<td><input type="password" name="retype" size=30></td>
		</tr>
  	</table>
  </div>

  <div class="quote box">Set these up to your tastes.</div>

  <div class="subtitle box">Paypal Express</div>
  <%= f.fields_for :paypal_account do |pp| %>
    <div class="fields">
  	<table>
		<tr>
			<td class="field_header"><%= pp.label :user %></td>
			<td> <%= pp.text_field :user%></td>
		</tr>
      		<tr>
			<td class="field_header"><%= pp.label :password %></td>
			<td> <%= pp.text_field :password%></td>
		</tr>
		<tr>
			<td class="field_header"><%= pp.label :signature %></td>
			<td><%= pp.text_field :signature%></td>
		</tr>
		<tr>
			<td class="field_header"><%= pp.label :currency %></td>
			<td><%= pp.text_field :currency %></td>
		</tr>
  	</table>
  <% end %>
  <div class="quote box">Using PayPal Express Checkout is pretty easy. Your PayPal account needs to have PayPal Express enabled. You can learn more about that <a href="https://merchant.paypal.com/us/cgi-bin/?cmd=_render-content&content_ID=merchant/express_checkout">here.</a></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shops/_menu.html.erb
<div class="titlebar shadow">
	<div class="title headline">Shop Manager</div>
	<%if @edit%>
	<div class="title menu <%if option == "shop"%>current<%else%>others<%end%>"><a href="/<%=params[:slug]%>/shops/edit/<%=@shop.id%>">My Shop</a></div>
	<div class="title menu <%if option == "stuff"%>current<%else%>others<%end%>"><a href="/<%=params[:slug]%>/stuffs/">My Stuff</a></div>
	<div class="title menu <%if option == "orders"%>current<%else%>others<%end%>"><a href="/<%=params[:slug]%>/orders/">My Orders</a></div>
	<div class="title menu "><a href="/login/logout/">logout</a></div>
	<%end%>
</div>

app/views/shops/edit.html.erb
<div class="contentbar">
	<%= render 'form' %>
</div>

app/views/shops/index.html.erb
  <%if notice%>
	  <p id="notice" style="display:none;"><%= notice %></p>
	  <script>
		$('#notice').slideDown(400);
		$('#notice').delay(4000).slideUp(400);
	  </script>
  <%end%>

    
  <div class="subtitle">Superette Shop List</div>
  
  <div class="fields">

<table style="padding:20px;">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Email</th>
    <th>Slug</th>
    <th></th>
  </tr>

<% @shops.each do |shop| %>
  <tr>
    <td><%= image_tag(gravatar_url(shop.email, {:size=>"25"})) %></td>
    <td><%= shop.name %></td>
    <td><%= shop.email %></td>
    <td><%= shop.slug %></td>
    <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
  </tr>
<% end %>
</table>
</div>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render 'form' %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Shop Name:</b>
  <%= @shop.name %>
</p>

<p>
  <b>Contact Email:</b>
  <%= @shop.email %>
</p>

<p>
 <b>Stock:</b>
 <%for stuff in @shop.stuffs%>
 <%=link_to stuff.name, stuff%><br />
 <%end%>
</p>

<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>